# Use this file to install dependencies for this image:

name: quast
channels:
  - bioconda
  - defaults
dependencies:
  - quast=5.0.2
  - circos
  - python
  - perl
  - blast
  - matplotlib-base
  - simplejson
  - zlib
  - joblib
  - glimmerHMM
  - openjdk >=8
  - minimap2 >=2.10
  
 
 
  
    
   
    
