# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml
name: seqkit
channels:
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - seqkit=0.14.0 
