# You can use this file to create a conda environment for this pipeline:
# this file is only needed if you are installing the package via conda
# conda env create -f environment.yml
name: BBTOOLS
channels:
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - bbmap
